server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://manny.db.elephantsql.com:5432/pokvxlhi
    username: pokvxlhi
    password: LiF4parkcvrZPJ-C4j6JC4M_kL7Ts4TG
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb+srv://user:DeEdgqXGvAMCd4YP@cluster0.peb9hqn.mongodb.net/Cluster0
      auto-index-creation: true