server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://manny.db.elephantsql.com:5432/pokvxlhi
    username: pokvxlhi
    password: LiF4parkcvrZPJ-C4j6JC4M_kL7Ts4TG
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#  data:
#    mongodb:
#      uri: mongodb://user:password@172.17.0.1:27017/mongo