server:
  port: 8080
  servlet:
    context-path: /contacts

spring:
  datasource:
    url: jdbc:postgresql://manny.db.elephantsql.com:5432/pokvxlhi
    username: pokvxlhi
    password: LiF4parkcvrZPJ-C4j6JC4M_kL7Ts4TG
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb+srv://user:DeEdgqXGvAMCd4YP@${spring.data.mongodb.database}.peb9hqn.mongodb.net/?retryWrites=true&w=majority
      database: cluster0